# Generated by Django 2.2.2 on 2019-09-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectversions',
            name='postman_link',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
