# Generated by Django 2.2.3 on 2019-07-19 10:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'member'), (2, 'guest'), (3, 'company')], default=2)),
            ],
            options={
                'db_table': 'user_type',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('usertype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nexiiapp.UserType')),
                ('user_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-updated_at'],
            },
            bases=('nexiiapp.usertype',),
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=255)),
                ('expired_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('browser_agent', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertoken_actor', to='nexiiapp.User')),
            ],
            options={
                'db_table': 'usertoken',
                'ordering': ['updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSecret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=255, null=True)),
                ('password', models.TextField(max_length=255, null=True)),
                ('reset_code', models.TextField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_secret_user_fk', to='nexiiapp.User')),
            ],
            options={
                'db_table': 'user_secrets',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_credit', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('actor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_credit_user', to='nexiiapp.User')),
            ],
            options={
                'db_table': 'user_credit',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_name', models.CharField(max_length=255)),
                ('original_name', models.CharField(max_length=255)),
                ('filepath', models.TextField()),
                ('extension', models.CharField(max_length=255)),
                ('filesize', models.CharField(max_length=255)),
                ('score', models.PositiveIntegerField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads_actor', to='nexiiapp.User')),
            ],
            options={
                'db_table': 'uploads',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('upload_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_upload_id', to='nexiiapp.Upload')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transactions', to='nexiiapp.User')),
            ],
            options={
                'db_table': 'user_transactions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technical_skills', django.contrib.postgres.fields.jsonb.JSONField()),
                ('job_role', models.CharField(max_length=255)),
                ('min_experience', models.DecimalField(decimal_places=2, max_digits=3)),
                ('max_experience', models.DecimalField(decimal_places=2, max_digits=3)),
                ('job_location', models.CharField(max_length=255, null=True)),
                ('min_budget', models.PositiveIntegerField(null=True)),
                ('max_budget', models.PositiveIntegerField(null=True)),
                ('notice_period', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('score', models.PositiveIntegerField()),
                ('actor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirement_actor', to='nexiiapp.User')),
            ],
            options={
                'db_table': 'requirements',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requirement_id', to='nexiiapp.Requirement')),
                ('upload_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_upload_id', to='nexiiapp.Upload')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_actor', to='nexiiapp.User')),
            ],
            options={
                'db_table': 'user_account_details',
                'ordering': ['-updated_at'],
            },
        ),
    ]
