# Generated by Django 2.2.3 on 2019-07-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexiiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredit',
            name='available_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
