# Generated by Django 2.2.3 on 2019-07-23 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nexiiapp', '0003_auto_20190723_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='requirement_id',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_requirement_id', to='nexiiapp.Requirement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='upload_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_upload_id', to='nexiiapp.Upload'),
        ),
    ]
