# Generated by Django 2.2.3 on 2019-07-24 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nexiiapp', '0006_auto_20190724_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='requirement_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_requirement_id', to='nexiiapp.Requirement'),
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='upload_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_upload_id', to='nexiiapp.Upload'),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='requirement_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_requirement_id', to='nexiiapp.Requirement'),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='upload_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_upload_id', to='nexiiapp.Upload'),
        ),
    ]
