# Generated by Django 2.2.3 on 2019-07-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexiiapp', '0007_auto_20190724_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'member'), (2, 'company')], default=1),
        ),
    ]
