# Generated by Django 2.2.3 on 2019-07-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexiiapp', '0008_auto_20190726_0545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='system_name',
        ),
    ]
