# Generated by Django 2.2.3 on 2019-07-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexiiapp', '0010_auto_20190729_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='download_filename',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='download_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
